### ISSUE TITLE
Disaini ühtlustamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#162]
**Tehtavate vaadete nimekiri:**

- [x] Sündmuse listvaade [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afc4340b3d126610f951f74) (https://github.com/hariduspilv/haridusportaal/issues/98, https://github.com/hariduspilv/haridusportaal/issues/126)
- [x] Sündmuse listvaade mobiil [Disaini link: filter kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afe907930a5d823224a983e) , [Disaini link: filter lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afe90795ad91520379787f9)
- [x] Sündmuse detailvaade [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afeba79e8d73e250f0df398) (https://github.com/hariduspilv/haridusportaal/issues/100, https://github.com/hariduspilv/haridusportaal/issues/110,  https://github.com/hariduspilv/haridusportaal/issues/2, https://github.com/hariduspilv/haridusportaal/issues/26)
- [x] Sündmuse detailvaade mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afeba7809a18d3d0f2bad4f)
- [x] Sündmuse kalendrivaade [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afe9801b7edeb431d83276e) (https://github.com/hariduspilv/haridusportaal/issues/99)
- [x] Uudise listvaade [Disaini link: filter kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbef090879ff66168809f5) , [Disaini link: filter lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afc28a8c384811f0fbb0036)
- [x] Uudise listvaade mobiil [disani link: filter kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbf8f9852cc3f615c79ec3), [disaini link: filter lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbf8f9852cc3f615c79ec3)
- [x] Uudise detailvaade [disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afaeaf6b65b0ccf0469f262)
- [x] Uudise detailvaade mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afc2398c384811f0fbab064)
- [x] artikli detailvaade + akordion [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afae7ba6a3720641549739e)
- [x] artikli detailvaade + akordion mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbfe2e6b31722f05e1c331)
- [x] Registreerimisvorm (sündmusele registreerimine) [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b028772c9c86cdf1eac582d), [Disaini link: error ja edukas protsess](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b0289a4c2fcab5116a619aa), [Disaini link: aitäh](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b045a86d08ed737014f7714)
- [x] Registreerimisvorm (sündmusele registreerimine) mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b028771a7c95c5e217822ed)
