### ISSUE TITLE
Dokumendivormil table tüüpi andmeelement

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#188]
- [x] Kuvada avatud sammu sees olevad **"table"** tüüpi andmeelemendid, sealhulgas:
- [x] Kuvada silt (_data_elements.data_element_name.title_)
***
- [x] Kuvada tabeli veerud (**_table_columns_** elemendid) , sealhulgas
- [x] Kuvada veeru päises pealkiri (_title_)
- Kuvada veeru väärtused (_value_) vastavalt andmetüübile:
- [x] veeru tüüp võib olla text (#174)
- [x] veeru tüüp võib olla number (#170)
- [x] veeru tüüp võib olla date (#184)
- [x] veeru tüüp võib olla checkbox (#185)
- [x] veeru tüüp võib olla selectlist (#187, tabelis ei ole mitmest valikut ehk _multiple_ lisatunnust)
- [x] veeru tüüp võib olla file (#230 , tabelis ei ole mitme faili võimalust ehk _multiple_ lisatunnust)
- [x] Kui veerul on lisatunnus _hidden_ väärtusega true , siis veergu  ei kuvata.
- [x] Kui _acceptable_activity_ on "SUBMIT" või "SAVE", kui avatud samm on _current_step_ ja veeru lisatunnus _readonly_ pole true, siis kuvada veerus väärtused muudetavana ning muul juhul mitte muudetavatena.
- [x] Kui veerul on lisatunnus _required_ väärtusega true, siis veeru pealkirja juures kuvada kohustuslikkuse märge.
***
- [x] Kui on abitekst (_helpertext_), siis kuvada andmeelemendi juures abiteksti sümbol (küsimärk), millele klikkides kuvatakse abitekst ( _kuidas abitekst sulgeda?_ )
- [x] Keele valiku arvestamine: tabeli ja veergude title, helpertext ja selectlist veerus option kuvada kasutaja valitud keeles. Kui dokumendis puudub kasutaja poolt valitud keeles, siis kuvada vaikekeeles (eesti keeles - 'et').
***
- [x] Kui tabelis mingis välja ei ole väärtust, siis väärtuste array-s esitatakse tühi väärtus. Iga veeru väärtuste array peab olema sama pikkusega.
