### ISSUE TITLE
Õppekavad (erialad) disain

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#228]
- [x]  õppekavade nimistu (https://github.com/hariduspilv/haridusportaal/issues/147, https://github.com/hariduspilv/haridusportaal/issues/148) [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1f90721f79c2d772503e13)
- [x]  õppekavade nimistu mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1f9179e490ad6a54337599)
- [x] õppekava detailvaade (https://github.com/hariduspilv/haridusportaal/issues/149, https://github.com/hariduspilv/haridusportaal/issues/150, https://github.com/hariduspilv/haridusportaal/issues/154) [Disaini link: sarnased erialad kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b266b3d7a17a83d684626e8), [Disaini link: sarnased erialad lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b266b3d3a42947a38b5876d)
- [x] õppekava detailvaade mobiil [Disaini link: sarnased erialad kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b26bc91d6f970ad28963178), [Disaini link: sarnased erialad lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b26be764b49720103c8aa72)
- [x] õppeasutuse õppekavad (https://github.com/hariduspilv/haridusportaal/issues/151) [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1396ae5c403c452a8f5a30)
- [x] õppeasutuse õppekavad mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b14da160f17ae5b3e60ad16)
- [x] õppekavade võrdlus (https://github.com/hariduspilv/haridusportaal/issues/153) [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b26b757c2f9e5b732c25d90)
- [x] õppekavade võrdlus mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b26ca58d443767461bc8724)

**Comment by birgitpulk** [comment]
Õppekavade nimistu: Ei ole sissejuhatavat teksti
Õppekavade nimistu mobiil: Alles jääb ainult nimi (kaob ära tekst ja "Lisa võrdlusesse" sektsioon)
