### ISSUE TITLE
Sündmuste kohendused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#308]
- [x] 	Sündmused > Kalendrivaade > üksiku sündmuse modaal võiks olla suurem, et pikem pealkiri jääks max kaherealiseks. Hetkel tundub modaal ikkagi liiga pisikene; Sündmused > Kalendrivaade > üksiku sündmuse modaal > sulgemise rist peaks olema üleval paremas nurgas
- [x] Sündmused > Kalendrivaade > 2 veel > modaal > hoveriga joon alla ainult üritusele mitte kellaajale ka 
- [x] Sündmused > listvaade> Lükkaks pealkirja all oleva halli teksti üksteise järele, jätaks kahe tekstikasti vaheks 48px. 
- [x] Sündmuse detailvaates ikkagi jääb 2 võimalust (registreeri ja salvesta kalendrisse). Kalendrisse salvestamine on lingina. Teksti alt ära kaotada download. 
- [x] Sündmusel registreerimise ja registreerunute nimistu väljastamise vormile disaini rakendamine.

**Comment by madispold** [comment]
Sündmuste registreerimise vorm ja registreerunute nimekirjaga tabel stiilitud.

Allalaadimiste dropdown tuleb eraldi, kuna see on sama element, mis kasutusel jagamise ehk share loogikal ja on teises piletis kirjas.

Registreerunute listi leiab hetkel sisse logides ja minnes lingile (muidugi saab registreerida ka mujale sündmustele, et sealgi esile tuleks): 
http://htm.twn.ee/et/sundmused/meeskonnatoo-tooalased-suhted-tookultuur

**Comment by madispold** [comment]
@birgitpulk @TanelTromp

**Comment by TanelTromp** [comment]
TEST

Viga 1: hoverdamisel ei teki "lingi käpakest" sulge "x" nupul:
https://gyazo.com/72a167a9ea25eec8fad69c82e3032206

Viga 2: kuigi on sisestatud vale e-posti aadress, laseb siiski sündmusele registreerida. "Saada" nupp peaks olema passiivne vms

Viga 3: sisestades telefoni, muutub väli roheliseks. Miks?
![pilt](https://user-images.githubusercontent.com/37407917/42305734-08472aaa-8035-11e8-8eb5-868694910e0e.png)

Viga 4: Sündmuse detailvaates ei kao "underlined" linkidel ("Lisa kalendrisse"; "e-posti aadress)  hoverdades nagu siin artiklis (mis on õige funktsionaalsus):
https://gyazo.com/bec6b8a229a1a89e23d94708af0149c1

Viga 5: Modaalil on nädalapäev inglise keelne:
![pilt](https://user-images.githubusercontent.com/37407917/42305746-11db8dea-8035-11e8-9c37-f4bb3c1aab10.png)

Viga 6: võiks kaaluda väljade maksimaalse pikkuse sisestamise piirangut. Nt 30 (v.a märkused). Kui nt kogemata kopi/peistiga midagi kaasa tuleb, siis ei lähe katki:
![pilt](https://user-images.githubusercontent.com/37407917/42305822-66825248-8035-11e8-93a5-733afe9bcda4.png)

Viga 7: sissepääsu info ja "salvesta kalendrisse" valik puudu (hetkel valitud: kutsetega):
![pilt](https://user-images.githubusercontent.com/37407917/42308505-6d7e4030-803e-11e8-91c5-059e93f526f8.png)

Viga 8: päevad detailvaates inglise keelsed

Viga 9: siin peaks olema "Organiseerija nimi", mitte asukoht (kirjutasin Skypes ka varem):
![pilt](https://user-images.githubusercontent.com/37407917/42308633-cf36cdf6-803e-11e8-8689-aa883da35874.png)

Viga 10: ei kuva "sündmuse asukoha linki":

![pilt](https://user-images.githubusercontent.com/37407917/42309239-b145e1d6-8040-11e8-90bd-ddad3490c860.png)

Viga 11: allalaadimise lingil hoverdades võiks tekkida ka hint, millega tegu. Muidu ei julgeta avada (Birgit otsustab).

![pilt](https://user-images.githubusercontent.com/37407917/42310281-ae366ca6-8043-11e8-8531-ccc758cfbf25.png)

@madispold @birgitpulk

**Comment by madispold** [comment]
Viga 2: Nupule disabled state lisatud, kuid hetkel vaid browseri enda äranägemise järgi hall värv küljes, @birgitpulk peaks pilgu heitma.

Vead 1 - 10 parandatud. @TanelTromp 

Viga 11 @birgitpulk

**Comment by madispold** [comment]
Testimisse.

**Comment by birgitpulk** [comment]
Viga 11: nõus
Viga 3: Millised need keerukamad väljad võiksid olla?

Osalejate nimekiri:
- [ ] Muutsin tabeli kujundust: https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b26b757c2f9e5b732c25d90
- [ ] Kas osalejate nimekirja puhul kui kõik tabeli tulbad on avatud, siis tabel ei muutu keritavaks? Mul on tunne et võiks muutuda, sest muidu pressib ta kõik väljad väga kokku. 
- [ ] Osalejate nimekirja kinniste tulpade avamise/sulgemise ikoonil võiks olla hoveriga tekst "Ava/Sulge tulp" vms
- [ ] Sorteerimine võiks olla tabeli tulba nimetuse kõrval üles-alla nooltega (+ tooltip hoveriga "Sorteeri A-Z" vms) 
- [ ] "Tagasi" nuppu ei ole kujunduses ette nähtud

Sündmuste filtreering:
- [ ] Välja pealkiri ja väljale klikkides välja pealkiri joone peal ei klapi
- [ ] Väljale kirjutades ja kui fookus ei ole enam väljal, siis kaob pealkiri joone pealt
- [ ] Datepickeri kalendri päevade nimetused inglisekeelsed. Lisaks võiks päeva nimetuse värvitoon olla #757575 (praegu ei vasta WCAG-le)
- [ ] Valitud sündmuse liigi "X" märk võiks olla sõna lõpus, tag'i sees ruumi paremalt ja vasakult 4px 
- [ ] Sündmuse liigid kasti sees paremas servas olev "X" märk võiks olla oranž nagu kalendri ikoon

Sündmuse detailvaade: 
- [ ] Detailvaates ei ole "Sündmused" menüü element valitud
- [ ] Kaardi +/- märk ja mehe ikoon peita

**Comment by madispold** [comment]
Testimisse @birgitpulk 

Viga 3: Jätsin rohelise tausta vaid nendele täidetud väljadele, mille puhul tekivad vead valel täitmisel ja käib vea tuvastus ehk registreerimise vormil vaid e-postile.

Viga 11: Kõik hoverdamised hetkel browseri enda tooltipidega - hoverdades väikse viivitusega tekib tekst. Kui vaja mingit üldist lahendust enda kujundusega lahendust, mida üle süsteemi kasutada, siis vaja luua plugin.

Tabel pea igal juhul hetkel keritav.

Mobiili vaates hetkel jäi "TAGASI", kuna ruumiga muidu ei tule välja, desktopis "TAGASI SÜNDMUSE VAATESSE"

""Valitud sündmuse liigi "X" märk võiks olla sõna lõpus, tag'i sees ruumi paremalt ja vasakult 4px"" - Ei saa sõna lõppu liigutada, paika pandud ng-select mooduliga, aga ruumi tekitasin.

Mobiilis lisatud tabelile nool, lõpuni kerides läheb peitu. Noolel vajutades liigub edasi ekraanilaiuse võrra.

**Comment by birgitpulk** [comment]
Üldine: 
- [ ] Muudame paremas tulbas olevate linkide loogikat: vaikimisi on lingid sinised ja ilma underline jooneta, hoveriga tekib joon alla (põhjus töölaua ja põhikutseala vaates kus paremale tulpa tekib väga mahukalt infot ja underline'ituna on see suht kirju)
- [ ] Breadcrumbs peaks olema 14px, hetkel 16px

Sündmuse detailvaade:
- [ ] "Saada" nupu disabled toonid: nupu taust #EEEEEE ja tekst #333333
- [ ] Registreerimisvormi modaal võiks olla md, lg ja xl ekraani suurusest sõltumatu ja igas suuruses ühesugune va väiksemad suurused, kus ta läheb kitsamaks
- [ ] "Toimumisaeg ja asukoht" tulba pealkiri peaks olema "Toimumisaeg ja -koht"
- [ ] Kas kaardi alt servast saab tekstid "Kaardiandmed" jne ära peita?
- [ ] Praktiline info tekstikastis on pealkirja ja sisuteksti vahe väiksem kui teistes kastides
- [ ] Kaardil ei ole piniga viidatud õige asukoht

Osalejate nimekiri: 
- [ ] Kui nimekiri on vasakule-paremale keritav, siis võiks olla ka nooled, mis indikeerivad kerimist
- [ ] Tabelis võiks olla nii palju tulpasid kinni, et tabel ei oleks vaikimisi keritav. 
- [ ] Sorteerimise noolele võiks tulla hiirega peale minnes ka kiri, millega tegu ("Sorteeri väljad A-Z" vms)

Sündmuse fitlreering: 
- [ ] Datepickeris võiks kuupäev alata kuu nimetuse suhtes järgmiselt realt
- [ ] Datepickeri päeva nimetus (E, T, K jne) võiks olla #757575 (hetkel inspect näitab et see on 38% mustast toonist)
- [ ] Parempoolsete kastide padding tekstikasti ja kasti alumise serva vahel peaks olema 24px (kas on Praktiline info kastis ka?)

**Comment by birgitpulk** [comment]
Taneli teemad ka testitud, olid ok kõik!

**Comment by heldiraudsepp** [comment]
@birgitpulk testib veel üle

**Comment by birgitpulk** [comment]
Muus osas ok, ainult üks teema jäi üles: 
Kalendri ruutude kõrgus teha väiksemaks, et kogu kalender mahuks ekraanile korraga (pidi muutuma ka loogika, et näidatakse 3 sündmust ja kui on üle 3 sündmuse, siis kolmanda sündmuse asemel tuleb kiri "... veel"

Kalender võiks olla valges kastis servast servani, aga muudame ruudud ristkülikuteks, ehk vähendame veelgi nende kõrgust.

@madispold

**Comment by madispold** [comment]
Kaotasin pixeleid ära ja tegin kitsamaks ja laiendasin kalendri kogu valgele kastile.
