### ISSUE TITLE
Kasutusjuhendi täiendused

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#340]
- [ ] teha #328 alusel avalehe kui sisutüübi haldamise kohta juhendisse juhend

- [ ] teha #379 alusel kasutusjuhendisse tõlgete haldamise kohta juhend.

Seotud töö: #464

**Comment by TanelTromp** [comment]
Ootab FE-tööd

**Comment by TanelTromp** [comment]
- [x] teha #328 alusel avalehe kui sisutüübi haldamise kohta juhendisse juhend

- [ ] teha #379 alusel kasutusjuhendisse tõlgete haldamise kohta juhend.
