### ISSUE TITLE
TEST leitud vead

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#382]
Viga 1: tablet (768 x 1260px - Windows 8.1 + Chrome 67) vaates on päis katki:

![pilt.png](https://images.zenhubusercontent.com/5ab8a6294b5806bc2bcc56d1/a23436df-275c-43b4-be40-8f4f8d8ee7f2)

Viga 2: IE11 päis katki:
![pilt.png](https://images.zenhubusercontent.com/5ab8a6294b5806bc2bcc56d1/725b87a0-f570-4873-b160-40cda9e4b0e2)

Viga 3: tabelite äärtes igalpool "scrollbarid", kuigi midagi ei ole kerida:
![pilt](https://user-images.githubusercontent.com/37407917/44399286-b86dc080-a54f-11e8-947e-fbc6d62be44c.png)

Viga 4: "List" vaadet eesti keeles ei ole, peab olema "Nimekiri":
![pilt](https://user-images.githubusercontent.com/37407917/44399306-cf141780-a54f-11e8-9b87-ea31c3f6a405.png)

Viga 5: "e" puudu:
![pilt](https://user-images.githubusercontent.com/37407917/44399380-10a4c280-a550-11e8-855d-da44c70a3363.png)

Viga 6: ei saa aru, et uudisepeapilt on klikitav st kursor ei muutu "käpaks" (ka sulgemise "x" sama teema):
https://gyazo.com/a13ca93761974010fc023b381c14b040

Viga 7: liiga heledad, ei vasta Zeplini kujundusele:

![7af2d8c7-55f1-41af-8bab-c25e69dd5678](https://user-images.githubusercontent.com/37407917/44655992-d334af00-a9ff-11e8-8f45-45deba3756b2.jpg)

Viga 8: lisada "Tagasi" nupp erialade võrdluse tabeli vaatesse (@birgitpulk )

Viga 9: Sündmuste kalendrimodaalis, "x" nupp vales kohas:

![pilt](https://user-images.githubusercontent.com/37407917/44769153-570baa00-ab6c-11e8-880b-39643d791cd6.png)

Viga 10: kindlasti peaks huuverdamisel mingi värvimuutus olema siin ikoonidel @birgitpulk 
https://gyazo.com/a17a36e06dd6e259ea3255587c1f5b72

**Comment by birgitpulk** [comment]
- [ ] Sakkidel võiks olla hover: ikoon + tekst tooniga #333333
- [ ] Otsingukast päises sisuga ühel joonel
- [ ] Uudiste kuupäeva filter katki (kinni panna kinni, siis jätab selle valituks, filtrist välja tulekuks pead tegema topeltkliki)
- [ ] Täpsem otsing ja temast vasakul oleva vormivälja vahe paigast ära (vt kujundust)
- [ ] Kuidas uudise sissejuhatuse tekst saab olla nii pikk, kas piirangut ei peaks peal olema? (http://htm.twn.ee/et/uudised/abbas-aptent) @TanelTromp ehk oskab ka kommenteerida?
- [ ] Külastatud link teist tooni: #D5401A 
- [ ] Uudise filter mobiil > Mis on vormiväljade fondi suurus? kas 14px?
- [ ] Sündmused > Kalender > modaalides ristid paigast ära, ristidel puudub hover (hover võiks olla #757575)
- [ ] Sündmused > Kalender > Kuuvahetus nooltel võiks olla hover (nt ümar ring taustal #eeeeee)
- [ ] Akordionite kujundus muutmata vaadetes
- [ ] Kui on ainult üks akordion, siis võiks ta olla vaikimisi kinni, kui rohkem kui üks, siis esimene lahti.
- [ ] Kõikides vaadetes parempoolses sidebaris kaotada sinistel linkidel joon alt ära. Valgetel linkidel jääb joon alles
- [ ] Jaga nupp: sinist tooni ikoon (#2E3374), hoveriga ümber ring siniseks, ikoon valgeks, samamoodi väiksemad fb jne ikoonid sinise taustaga. ikoonidele minnes hover toon #454B92
- [ ] Filtreeringus “Täpsem otsing” hover puudu (joon alt ära)
- [ ] Päises kolme täppi ikoon: hover ring tooniga #454B92
- [ ] Päises logole minnes tekib sellele sinine kast ümber, miks?
- [ ] Otsikasti sees info “Otsi märksõna järgi ja vajuta Enter”
- [ ] Md variandil kaotada ka Logi sisse ikooni juurest ära, hover sama nagu kolme täpiga ikooni puhul
- [ ] Avalehel hover võiks olla terve uudise ulatuses (foto ka)
- [ ] Avaleht > Uudiskiri > Nupu laius alati sama (vt kujundust), ekraanilaiuse muutumisel muutub vormivälja laius, mitte nupu laius
- [ ] Hetkel tundub et avalehel alla 1280px on juba xs, teistel vaadetel on xs alla 900px

**Comment by birgitpulk** [comment]
Õppeasutused listvaade: 
- [ ] Suurendada reavahet õppasutuse pealkirja ja selle all oleva teksti vahel
- [ ] Filtris muutub disabled välja peal klikkides selle välja sees olev tekst siniseks

**Comment by madispold** [comment]
@TanelTromp 
Vead 1-10: OK
Viga 1 kommentaar: Tekkis samasugune tõlgete probleem vaid 3G ühendust simuleerides, muidu oli OK mul. Reaalselt küll tabletiga ei testinud.
Viga 10 kommentaar: Lisasin hetkel hoveriks nuppudel lehe oranži tooni taustaks. @birgitpulk peaks kindlasti üle käima.

**Comment by TanelTromp** [comment]
Viga 2: endiselt valesti joondatud otsingukast IE11:

![pilt](https://user-images.githubusercontent.com/37407917/44787949-52adb400-aba1-11e8-8d3c-c42812a06b72.png)

Viga 8: nupu asukoht ikka ilmselt all vasakul, mitte üleval paremal? @birgitpulk 

![pilt](https://user-images.githubusercontent.com/37407917/44788081-b89a3b80-aba1-11e8-91ff-5a6a7dbd9b82.png)

Viga 1 uus: erialade modaali veateade tühi, kas see on tõlgete probleem?

![pilt](https://user-images.githubusercontent.com/37407917/44788154-f303d880-aba1-11e8-9842-43e0ac3ff517.png)

**Comment by birgitpulk** [comment]
Viga 8: jah nupp üleval paremal, sest tabel võib minna väga pikaks ja siis ei pruugi kasutaja selle nupuni jõudagi @TanelTromp

**Comment by TanelTromp** [comment]
Uus vana viga 1: "ürituse tüüp" välja väärtust kuvatakse vastava taksonoomia "tagina" ürituse teiste tagide juures:

![pilt](https://user-images.githubusercontent.com/37407917/44790302-b4711c80-aba7-11e8-9d2d-7278e72713be.png)

**Comment by madispold** [comment]
Uus vana viga 1: OK.
