### ISSUE TITLE
Dokumentide (taotlused, otsused) kuvamine töölaual

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#394]
**Üldkirjeldus:**
Kasutaja näeb enda taotluste andmeid ja saab alustada taotluste sisestamist.

**Eeltingimused ja käivitamine:**
- Kasutaja on portaali sisse loginud. Portaalis on teada kasutaja isikukood.
- Portaal avab töölaua kasutajale pärast sisse logimist.
- Taotluste nägemiseks kasutaja valib töölaual "Taotlused"

**Tegevused:**
* Taotluste saamiseks tehakse back-end-st päring _applications_ (vt #391). Saadud dokumentide andmed kuvatakse kolmes osas.
***
Esitatavad taotlused (_applications_ päringu vastuses objekt _acceptable_forms_):
- [x] Kuvatakse esitatavate taotluste "kaardid"
- [x] Iga esitatava taotluse kohta kuvatakse nimetus (_title_) kasutaja pool valitud keeles või kui selles keeles _title_ puudub, siis 'et' keeles.
- [x] Kasutaja saab alustada dokumendivormi sisestamist (#425; URL... /xjson/_form_name_)
- [x] Esitatavad taotlused kuvatakse nimetuste (_title_) järjekorras (kaartide järjekord jookseb "ridu pidi" ehk järjekord liigub esmalt vasakult paremale ja teiseks ülalt alla).
- [x] Vaikimisi kuvatakse kuni 4 esitatavat taotlust. Kui esitatavaid taotlusi on rohkem kui 4, siis kuvatakse "näita rohkem (nn)", nn on peidus olevate esitatavate taotluste arv (koguarv - 4). "Näita rohkem" peale klikkides kuvatakse kõik esitatavad taotlused. 
- [x] Kui päringu tulemusena ei saadud ühtegi esitatava taotluse kirjet, siis kuvatakse teade "Praegu ei saa esitada ühtegi taotlust".
- Disainis näha olevat esitamise tähtaega praegu pole. 
***
Pooleli olevad taotlused (_applications_ päringu vastuses objekt _drafts_):
- [x] Kuvatakse pooleli olevate taotluse tabel
- [x] Iga pooleli oleva taotluse kohta kuvatakse nimetus (_title_) kasutaja pool valitud keeles või kui selles keeles _title_ puudub, siis 'et' keeles.
- [x] Pooleli taotlused kuvatakse nimetuste järjekorras.
- [x] Kasutaja saab jätkata dokumendivormi sisestamist. 
-- FE teeb dokumendi mustandi saamiseks BE-st xsjon päringu (#240) sisenditega: _draft_ = true, _form_name_ ja _identifier_.
-- FE avab dokumendi sisestamise ekraanivormi kasutades päringu vastust.
- [x] Kui _applications_  päringu (#391) tulemusena ei saadud ühtegi pooleli oleva taotluse kirjet, siis kuvatakse teade "Pooleli olevaid taotlusi ei ole".
***
Taotlused ja otsused (_applications_ päringu vastuses objekt _documents_):
- [x] Kuvatakse taotluse ja otsuste tabel
- [x] Taotluse või otsuse kohta kuvatakse nimetus (_title_), kuupäev (_document_date_) ja staatus (_status_). Nimetus kuvatakse kasutaja pool valitud keeles või kui selles keeles _title_ puudub, siis 'et' keeles
- [x] Taotluse või otsuse kohta on olemas kirjeldus (_description_), siis see kuvatakse eelnevalt nimetatud andmete all eraldi real.
- [x] Taotlused ja otsused kuvatakse kuupäevade järjekorras kahanevalt (uuemad eespool).
- [x] Kasutaja saab alustada dokumendi vaatamist. 
-- FE teeb dokumendi saamiseks BE-st xsjon päringu (#240) sisenditega: _existing_ = true, _form_name_ ja _identifier_.
-- FE avab dokumendi sisestamise ekraanivormi kasutades päringu vastust (kuna _acceptable_activity_ on "VIEW", siis sisestamise ekraanivorm töötab antud juhul kuvamise ekraanivormina).
- [x] Kui _applications_ päringu (#391) tulemusena ei saadud ühtegi taotluse või otsuse kirjet, siis kuvatakse teade "Dokumente ei ole".

***
[Disaini link](https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b7ea5971d6b03591e0547e2)

**Comment by birgitpulk** [comment]
Visuaalsed vead: 
- [ ] Tabeli paddingud peaksid olema 10px (igalpool mujal 10)
- [ ] "Jätka täitmist " peaks olema rohkem paremal (ehk et tabel ei oleks visuaalselt pooleks tehtud)
- [ ] Tabeli kohal oleva pealkirja ja tabeli vaheline ruum peaks olema 8px
- [ ] Taotlused ja otsused tabelis peaks olema kommentaari väli Regular ja eraldatud joontega 2px #757575
- [ ] Taotlused ja otsused tabeli kommentaari paddingud ka paigast ära
- [ ] Mobiilis Näita rohkem ja viimase nupu vaheline ruum peaks olema 32px
- [ ] Mobiilis keritavate tabelite puhul nooled puudu ja tabelid ei ole keritavad

**Comment by TanelTromp** [comment]
TEST

Viga 1: (UHD-l) täislaiuses on siltide sortimine katki:
![capture](https://user-images.githubusercontent.com/37407917/47092154-08ef5a80-d22f-11e8-8121-45c4f84397b4.PNG)

**Comment by srautam** [comment]
Viga 1: Korras

**Comment by TanelTromp** [comment]
TEST

**Eeltingimused ja käivitamine:**
- [x] - Kasutaja on portaali sisse loginud. Portaalis on teada kasutaja isikukood.
- [x] - Portaal avab töölaua kasutajale pärast sisse logimist.
- [ ] - Taotluste nägemiseks kasutaja valib töölaual "Taotlused" **Uus töölaua loogika, ehk enam "taotlusi valima" eraldi ei pea**

**Tegevused:**
- [ ]* Taotluste saamiseks tehakse back-end-st päring _applications_ (vt #391). Saadud dokumentide andmed kuvatakse kolmes osas. **Testitud DUMMY dataga ehk päringut sellisel kujul ei toimu**
**
Esitatavad taotlused (_applications_ päringu vastuses objekt _acceptable_forms_):
- [x] Kuvatakse esitatavate taotluste "kaardid"
- [x] Iga esitatava taotluse kohta kuvatakse nimetus (_title_) kasutaja pool valitud keeles või kui selles keeles _title_ puudub, siis 'et' keeles. **Mitmekeelsust selles faasis enam ei ole**
- [ ] Nimetusele klikkides käivitub dokumendivorm sisestamine (#425; URL... /xjson/_form_name_) **URL on muutunud ja nõue enam ei kehti""
- [x] Esitatavad taotlused kuvatakse nimetuste (_title_) järjekorras (kaartide järjekord jookseb "ridu pidi" ehk järjekord liigub esmalt vasakult paremale ja teiseks ülalt alla).
- [x] Vaikimisi kuvatakse kuni 4 esitatavat taotlust. Kui esitatavaid taotlusi on rohkem kui 4, siis kuvatakse "näita rohkem (nn)", nn on peidus olevate esitatavate taotluste arv (koguarv - 4). "Näita rohkem" peale klikkides kuvatakse kõik esitatavad taotlused. 
- [x] Kui päringu tulemusena ei saadud ühtegi esitatava taotluse kirjet, siis kuvatakse teade "Praegu ei saa esitada ühtegi taotlust".
- [x] Disainis näha olevat esitamise tähtaega praegu pole. 
***
Pooleli olevad taotlused (_applications_ päringu vastuses objekt _drafts_):
- [x] Kuvatakse pooleli olevate taotluse tabel
- [x] Iga pooleli oleva taotluse kohta kuvatakse nimetus (_title_) kasutaja pool valitud keeles või kui selles keeles _title_ puudub, siis 'et' keeles. **Mitmekeelsust selles faasis enam ei ole**
- [x] Pooleli taotlused kuvatakse nimetuste järjekorras.
- [ ] Nimetusele klikkides saab jätkata dokumendivormi sisestamist.   **Nõue enam ei kehti. Avatakse "Ava" või "Jätka täitmist**
-- FE teeb dokumendi mustandi saamiseks BE-st xsjon päringu (#240) sisenditega: _draft_ = true, _form_name_ ja _identifier_.
-- FE avab dokumendi sisestamise ekraanivormi kasutades päringu vastust.
- [x] Kui _applications_  päringu (#391) tulemusena ei saadud ühtegi pooleli oleva taotluse kirjet, siis kuvatakse teade "Pooleli olevaid taotlusi ei ole".
***
Taotlused ja otsused (_applications_ päringu vastuses objekt _documents_):
- [x] Kuvatakse taotluse ja otsuste tabel
- [x] Taotluse või otsuse kohta kuvatakse nimetus (_title_), kuupäev (_document_date_) ja staatus (_status_). Nimetus kuvatakse kasutaja pool valitud keeles või kui selles keeles _title_ puudub, siis 'et' keeles **Mitmekeelsust selles faasis enam ei ole**
- [x] Taotluse või otsuse kohta on olemas kirjeldus (_description_), siis see kuvatakse eelnevalt nimetatud andmete all eraldi real.
- [x] Taotlused ja otsused kuvatakse kuupäevade järjekorras kahanevalt (uuemad eespool).
- [ ] Nimetusele klikkides saab alustada dokumendi vaatamist. **Nõue enam ei kehti. Avatakse "Ava" või "Jätka täitmist**
-- FE teeb dokumendi saamiseks BE-st xsjon päringu (#240) sisenditega: _existing_ = true, _form_name_ ja _identifier_.
-- FE avab dokumendi sisestamise ekraanivormi kasutades päringu vastust (kuna _acceptable_activity_ on "VIEW", siis sisestamise ekraanivorm töötab antud juhul kuvamise ekraanivormina).
- [x] Kui _applications_ päringu (#391) tulemusena ei saadud ühtegi taotluse või otsuse kirjet, siis kuvatakse teade "Dokumente ei ole".

**Comment by birgitpulk** [comment]
- [ ] Kui taotlusi ei ole, siis võiks olla tabel ikka kuvatud (esimene rida) ja teisel real olla keskele joondatud info "Pooleliolevaid taotlusi ei ole"

**Comment by birgitpulk** [comment]
- [ ] Tabelid ei ole keritavad mobiilis
- [ ] "Näita vähem" nupu ees võiks olla "-" märk ka

**Comment by madispold** [comment]
@birgitpulk @TanelTromp 
n arv tabelite kerimine realiseeritud:
http://htm.twn.ee/et/toolaud/taotlused/TESTIMISEKS2210?test=true

**Comment by madispold** [comment]
@birgitpulk Tabelid keritavad.

**Comment by birgitpulk** [comment]
- [ ] Näita rohkem ja Näita vähem nupu ala on liiga suur

<img width="758" alt="screen shot 2018-10-30 at 11 19 35" src="https://user-images.githubusercontent.com/24669779/47708072-f533f300-dc35-11e8-87c3-aa8a5e4dea79.png">
