### ISSUE TITLE
Sisuhalduses saab toimetada OSKA valdkonna detailvaadet

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#450]
**Eesmärk, üldkirjeldus:**
Sisuhalduses saab luua ja toimetada OSKA valdkonna „FieldPage“ mallil sisulehte.

Sisuleht erineb Artikkel tüüpi sisulehest selle poolest, et selle sisutüübiga saab siduda infograafika kuvamise ja erinevad parema veeru elemendid, mis realiseeritakse piletis #496.
Sarnane sisutüüp on põhikutseala ehk „MainProfessionPage“, erinevus on selles, et valdkonna lehele ei lisata silte.

**Eeltingimused ja käivitamine:**
- Kasutajal on sisuhalduri õigused.
- Kasutaja on sisuhaldurina sisse loginud.

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- [ ] toimetada lehe sisu 
- [ ] vaadata sisulehe eelvaadet ilma seda lehekülge veebi külastajatele avaldamiseta
- [ ] siduda sisulehte menüüpunktiga
- [ ] avaldada sisulehte
- [ ] saab lisada pildi, mida kuvatakse üksnes nimekirja vaates (nõue lisatud planeerimisel)

**Sisulehe põhiosa elemendid:**
- [ ] pealkiri (title), kohustuslik, maksimaalne pikkus 50
- [ ] sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- [ ] video - vabatahtlik
- [ ] sisu (content) - kohustuslik, WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] lingid - webPageLink, nimetus ja URL, võib olla mitu (välised lingid), vabatahtlik
- [ ] lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu, vabatahtlik
- [ ] pilt (picture) - vabatahtlik; pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud, max arv 2
- [ ] infograafika - vabatahtlik - kirjeldatud #468 

**Sisulehe alamosa elemendid:**
Sarnaselt Artikkel tüüpi lehele. Lisamine on vabatahtlik, lehel võib olla mitu alamosa (akordion). Kui lisatakse, siis:
- [ ] alamlehe (alamosa) jrk (paragraphSecuenceNo), kohustuslik,
- [ ] alampunkti (alamosa) pealkiri (paragraphTitle), kohustuslik, maksimaalne pikkus 50
- [ ] alamlehe (alamosa) sisu (paragraphContent), kohustuslik, - WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] alamlehe (alamosa) link - webPageLink, nimetus ja URL, võib olla mitu, vabatahtlik
- [ ] alamlehe sees infograafika - vabatahtlik - kirjeldatud #468 
   
**Viited:**
parem veerg: #496
kuvamine: #451 
nimistu: #476 
disain: https://zpl.io/2ZzOYOd

**Comment by TanelTromp** [comment]
Viga 1: funktsionaalsus puudub: _siduda sisulehte menüüpunktiga_

Viga 2: maksimaalse pikkuse nõue täitmata "pealkiri" väljal: _pealkiri (title), kohustuslik, maksimaalne pikkus 50_

Viga 3: akordioni lisamine on kohustuslik, ei tohiks olla

Viga 4: maskimaalse pikkuse nõue täitmata "Sissejuhatav tekst" väljal. _sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text_

Viga 5: üldine ja edaspidi - kes tõlgib väljade nimetused vastavalt piletis olevatele?

Viga 6: video lisamine peaks olema üks võimalik, hetkel kaks

**Comment by lsoonvald** [comment]
Võib uuesti proovida.

**Comment by TanelTromp** [comment]
Viga 2: maksimaalse pikkuse nõue täitmata "pealkiri" väljal: pealkiri (title), kohustuslik, **maksimaalne pikkus 50**

Viga 3: akordioni lisamine on kohustuslik, ei tohiks olla

Viga 4: maskimaalse pikkuse nõue täitmata "Sissejuhatav tekst" väljal. sissejuhatav tekst (introduction), vabatahtlik, **maksimaalne pikkus 300**, plain-text

Viga 10: sisuhaldurina ei saa seda sisutüüpi lisada

Viga 11: saab lisada ainult ühe pildi, peab saama lisada kaks. _pilt (picture) - vabatahtlik; pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad kohustuslikud_, **max arv 2**



-------------------------------------

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- [ ] toimetada lehe sisu 
- [ ] vaadata sisulehe eelvaadet ilma seda lehekülge veebi külastajatele avaldamiseta
- [ ] siduda sisulehte menüüpunktiga
- [ ] avaldada sisulehte
- [ ] saab lisada pildi, mida kuvatakse üksnes nimekirja vaates (nõue lisatud planeerimisel)

**Sisulehe põhiosa elemendid:**
- [ ] pealkiri (title), kohustuslik, maksimaalne pikkus 50
- [ ] sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- [ ] video - vabatahtlik
- [ ] sisu (content) - kohustuslik, WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] lingid - webPageLink, nimetus ja URL, võib olla mitu (välised lingid), vabatahtlik
- [ ] lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu, vabatahtlik
- [ ] pilt (picture) - vabatahtlik; pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud, max arv 2
- [ ] infograafika - vabatahtlik - kirjeldatud #468 

**Sisulehe alamosa elemendid:**
Sarnaselt Artikkel tüüpi lehele. Lisamine on vabatahtlik, lehel võib olla mitu alamosa (akordion). Kui lisatakse, siis:
- [ ] alamlehe (alamosa) jrk (paragraphSecuenceNo), kohustuslik,
- [ ] alampunkti (alamosa) pealkiri (paragraphTitle), kohustuslik, maksimaalne pikkus 50
- [ ] alamlehe (alamosa) sisu (paragraphContent), kohustuslik, - WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] alamlehe (alamosa) link - webPageLink, nimetus ja URL, võib olla mitu, vabatahtlik
- [ ] alamlehe sees infograafika - vabatahtlik - kirjeldatud #468
