### ISSUE TITLE
Sisuhalduses saab toimetada OSKA ametiala (põhikutseala) detailvaadet

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#452]
**NB! põhikutseala = ametiala**

**Eesmärk, üldkirjeldus:**
Sisuhalduses saab luua ja toimetada OSKA_põhikutseala „MainProfessionPage“ mallil sisulehte.

Sisuleht erineb Artikkel tüüpi sisulehest selle poolest, et selle sisutüübiga saab siduda infograafika kuvamise ja erinevad parema veeru elemendid, mis realiseeritakse piletis #494.

**Eeltingimused ja käivitamine:**
- Kasutajal on sisuhalduri õigused.
- Kasutaja on sisuhaldurina sisse loginud.

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- [ ] toimetada lehe sisu 
- [ ] vaadata sisulehe eelvaadet ilma seda lehekülge veebi külastajatele avaldamiseta
- [ ] siduda sisulehte menüüpunktiga
- [ ] avaldada sisulehte

**Sisulehe põhiosa elemendid:**
- [ ] pealkiri (title), kohustuslik, maksimaalne pikkus 50
- [ ] märge (fixedLabel), vabatahtlik, kuni 50 tähemärki silt, mida saab kas külge lisada või mitte. Haldamine oleks taksonoomiate alt (võib lahendada teisiti), oluline on, et nimekirja vaates saaks kuvada esile toomist - vt näidet "Tuleviku ala" https://zpl.io/bLDo836  - selle alusel filter nimekirjas
- [ ] sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- [ ] video - vabatahtlik, max arv 2
- [ ] sisu (content) - kohustuslik, WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] lingid - webPageLink, nimetus ja URL, võib olla mitu (välised lingid), vabatahtlik
- [ ] lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu, vabatahtlik
- [ ] pilt (picture) - vabatahtlik; pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud
- [ ] infograafika - vabatahtlik - kirjeldatud #468 
- [ ] silt (label), vabatahtlik, maksimaalne arv 5 - nii nagu on sündmuse/uudise/artikkel sisu osas all sildid. Ja muuta taksonoomiaks, et tagada samade siltide kasutamine.

**Sisulehe alamosa elemendid:**
Sarnaselt Artikkel tüüpi lehele. Lisamine on vabatahtlik, lehel võib olla mitu alamosa (akordion). Kui lisatakse, siis:
- [ ] alamlehe (alamosa) jrk (paragraphSecuenceNo), kohustuslik,
- [ ] alampunkti (alamosa) pealkiri (paragraphTitle), kohustuslik, maksimaalne pikkus 50
- [ ] alamlehe (alamosa) sisu (paragraphContent), kohustuslik, - WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] alamlehe (alamosa) link - webPageLink, nimetus ja URL, võib olla mitu, vabatahtlik
  
Viited:
parem veerg: #494
kuvamine: #453 
nimistu: #477 
disain: https://zpl.io/V41Wg1M

**Comment by TanelTromp** [comment]
Viga 1: pealkirja pikkus ei ole piiratud, peab olema kuni 50 tähemärki (counter ka puudu)

Viga 2: pikkus ei ole hetkel piiratud _sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300,_ 

Viga 3: Lisada saab hetkel ainult ühe aga peab saama lisada unlimited + kui tegemist on ainult väliste linkide lisamisega, siis "autocomplete" funktsioon eemaldada. Hetkel jääb loader saagima. _lingid - webPageLink, nimetus ja URL, võib olla mitu (välised lingid), vabatahtlik_

Viga 4: hetkel saab lisada mitut pilti, peab saama ainult ühe

Viga 5: kuidagi liiga palju OSKA Graph välju on lahti (ei ole ise lisanud) + kui mingi väärtus on lisatud, siis ei saa kustutada enam:
https://gyazo.com/65948954fffd1ce460bcd05409d2c1ea

**Comment by lsoonvald** [comment]
Võib uuesti proovida.

**Comment by TanelTromp** [comment]
Viga 9: sisuhalduril puuduvad õigused seda sisu lisada ("sisuhaldurtanelile")

Täpsustus 1:: kas eemaldasid infograafika väljad sellepärast, et see teeb päringu katki? Need võiks olemas olla (põhisisu+akordion) ja ma neid lihtsalt ei näpi
