### ISSUE TITLE
Üldistatud dokumendivormid disaini rakendamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#466]
Realiseeritud/realiseeritavad funktsionaalsuse piletid:
- [x] Dokumendivormi päis ja sammud https://github.com/hariduspilv/haridusportaal/issues/169
- [x] Nupud https://github.com/hariduspilv/haridusportaal/issues/171
- [x] Teated https://github.com/hariduspilv/haridusportaal/issues/172
- [x] Heading, helpertext,  https://github.com/hariduspilv/haridusportaal/issues/173
- [x] Text, textarea https://github.com/hariduspilv/haridusportaal/issues/174
- [x] Number https://github.com/hariduspilv/haridusportaal/issues/170
- [x] Date https://github.com/hariduspilv/haridusportaal/issues/184
- [x] Checkbox https://github.com/hariduspilv/haridusportaal/issues/185
- [x] Email  https://github.com/hariduspilv/haridusportaal/issues/186
- [x] Tabel

[Disaini link - sammud](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b3f0fe60f5d54d011f9c1af)
[Disaini link - teated](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b3f0fe5527f910aa2354b9f)

**Comment by birgitpulk** [comment]
**Visuaalsed vead DESKTOP** 

Viisard:
- [ ] Samm, mille peal ollakse, selle sammu pealkirja tekst ei ole link (visuaalselt ka)
- [ ] Järgnevad sammud (mida ei ole täidetud veel) ei ole ka lingid (peaksid olema #757575 tooni)

Esimene samm:
- [ ] Muuda nupu all olev teksti reavahe on 24, aga peaks olema 22
- [ ] Vahepealkirja all oleva sissejuhatava teksti reavahe on 16, aga peaks olema 22
- [ ] Vormiväljale vajutades kui ei saa saa väljale kirjutada, siis võiks tekkida tooltip, mis viitab, et "Info muutmiseks vajuta vormi kohal olevat Muuda nuppu vms" (Arutada Andrusega täpne sõnastus)
- [ ] "Järgmine" nupu teksti suurus peab olema 16px
- [ ] "Järgmine" nupu asukoht võiks olla "Muuda" nupu all (ei ole seotud nupud, praegune asukoht tekitab segadust)
- [ ] Vormiväljade sees oleva teksti toon (kui olen välja sisse midagi kirjutanud, mitte placeholder) peaks olema #333333 ja Light, vormivälja joone pealne tekst Ragular ja #333333

Muuda nupule vajutades avanev modaal: 
- [ ] Modaali sees olev tekst peaks olema joondatud keskele
- [ ] Modaalil peab olema paremas ülaservas sulgemise rist
- [ ] Modaalil peab olema pealkiri (nt TAOTLUSE VORMI MUUTMINE vms)
- [ ] Modaalis kuvatakse tekst suurusega 24px
- [ ] "Jah" nupp peaks olema CTA nupp
- [ ] Nupp ei saa olla lihtsalt "Jah", vaid peaks olema a'la "Jah, soovin andmeid muuta" (Arutada Andrusega täpset sõnastust)

**Comment by birgitpulk** [comment]
Visuaalsed vead vol2: 

- [ ] "Esimene samm" kiri: lingil peab olema joon all ning kaduma, kui hiirega peale minna

**Comment by birgitpulk** [comment]
- [ ] Kui checkboxi tekst (14px) muutub mitmerealiseks, siis peaks reavahe (line-height) olema 18px

**Comment by madispold** [comment]
@birgitpulk 

"Samm, mille peal ollakse, selle sammu pealkirja tekst ei ole link (visuaalselt ka)": OK.
"Vormivälja ja sellele JÄRGNEVA vahepealkirja vahe peaks olema suurem": Panin vastavalt kujundusele 32px iga pealkirja ette.
Visuaalsed vead vol2: OK.

Kui checkboxi tekst (14px) muutub mitmerealiseks, siis peaks reavahe (line-height) olema 18px: Pole inimlikku lahendust siin, et jälgida kõiki checkbox välju ning lisaks kas nad murduvad konkreetses viewportis.

**Comment by birgitpulk** [comment]
- [ ] "Lohista failid siia või" teksti suurus peaks olema 14 px ja värv #333333
- [ ] Datepickeri kast avaneb ikoonist liiga kaugele
- [ ] VPT taotlus > Sissetulekud > Tabeli sees olev vormiväli peaks olema kandiline, aga ümarate nurkadega. Lisaks tekib sinna olukord, kus tabeli pealkiri on üks ja vormivälja kirjeldus on teine (sellist lahendust ei ole ma ette näinud ja see ei ole hea)
- [ ] VPT > Esitamise tulemus > Kui väljasid ei saa muuta, siis ei tohiks datepicker jms ikoone välja sees olla

**Comment by madispold** [comment]
Datepickeri kast avaneb ikoonist liiga kaugele: Ei leidnud dokumentatsioonist varianti seda muuta, materiali datepickeri automaatika seab avaneva kasti olenevalt viewportist välja külge ja kahjuks vasakule, ei näe siin lahendust :(

VPT taotlus > Sissetulekud > Tabeli sees olev vormiväli peaks olema kandiline - JSON struktuuri alusel pole sisestusväli tabelis, vaid eraldi ning seetõttu ka standard välimusega.

Ülejäänud 2: OK.

http://htm.twn.ee/et/toolaud/taotlused/VPT_TAOTLUS?test=true
http://htm.twn.ee/et/toolaud/taotlused/TESTIMISEKS2210?test=true

**Comment by birgitpulk** [comment]
@madispold 

1. Dropdown väljadel peaks olema välja pealkiri placeholder tekstina välja sees ja liikuma joone peale kui väljale klikitakse < Kas on näidet kusagil?

2. VPT taotlus > Sissetulekud > Tabeli sees olev vormiväli peaks olema kandiline - JSON struktuuri alusel pole sisestusväli tabelis, vaid eraldi ning seetõttu ka standard välimusega. < Varem olid need kandilised?

3. Kas tooltipid avanevad mobiilses vaates klikiga? Kuidas sulguvad? Hetkel jäävad visuaalselt nurga taha ka.

**Comment by birgitpulk** [comment]
Kujundus ok, vaatasin üle.
