### ISSUE TITLE
OSKA ülduuringu lehekülje toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#474]
**Eesmärk, üldkirjeldus:**
Sisuhalduses saab luua ja toimetada OSKA valdkonna „SurveyPage“ mallil sisulehte.
See on nö universaalne lk erinevate OSKA teemade jaoks, kus kuvatakse mh infograafikat.

**Eeltingimused ja käivitamine:**
- Kasutajal on sisuhalduri õigused.
- Kasutaja on sisuhaldurina sisse loginud.

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- [ ] toimetada lehe sisu 
- [ ] vaadata sisulehe eelvaadet ilma seda lehekülge veebi külastajatele avaldamiseta
- [ ] siduda sisulehte menüüpunktiga
- [ ] avaldada sisulehte

**Sisulehe põhiosa elemendid:**
- [ ] pealkiri (title), kohustuslik, maksimaalne pikkus 50
- [ ] sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- [ ] video - vabatahtlik, max arv 2
- [ ] sisu (content) - kohustuslik, WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] lingid - webPageLink, nimetus ja URL, võib olla mitu (välised lingid), vabatahtlik
- [ ] lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu, vabatahtlik
- [ ] pilt (picture) - vabatahtlik; pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud, max arv 2
- [ ] infograafika - vabatahtlik - kirjeldatud #468  - n arv

**Sisulehe alamosa elemendid:**
Sarnaselt Artikkel tüüpi lehele. Lisamine on vabatahtlik, lehel võib olla mitu alamosa (akordion). Kui lisatakse, siis:
- [ ] alamlehe (alamosa) jrk (paragraphSecuenceNo), kohustuslik,
- [ ] alampunkti (alamosa) pealkiri (paragraphTitle), kohustuslik, maksimaalne pikkus 50
- [ ] alamlehe (alamosa) sisu (paragraphContent), kohustuslik, - WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] alamlehe (alamosa) link - webPageLink, nimetus ja URL, võib olla mitu, vabatahtlik
- [ ] alamlehe sees infograafika - vabatahtlik - kirjeldatud #468 
   
**Parema veeru elemendid**
- [ ] Sisulehele saab (aga ei pea) lisada parema veeru elemendid, mis vastavad TypeOneArticlePage malli paremale veerule (vt #181 ).

**Viited:**
kuvamine: #475

**Comment by EgleM-TW** [comment]
Tingimused on copy-paste OSKA valdkonna lk tüübiga.
Video puhul lähtume samast lahendusest nagu Artikkel tüübi puhul (ehk kuvamisel sisuteksti all), lisan selle FE piletisse ka.

**Comment by TanelTromp** [comment]
**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- [x] toimetada lehe sisu 
- [x] vaadata sisulehe eelvaadet ilma seda lehekülge veebi külastajatele avaldamiseta
- [x] siduda sisulehte menüüpunktiga
- [x] avaldada sisulehte

**Sisulehe põhiosa elemendid:**
- [x] pealkiri (title), kohustuslik, maksimaalne pikkus 50
- [x] sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- [x] video - vabatahtlik, max arv 2
- [x] sisu (content) - kohustuslik, WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [x] lingid - webPageLink, nimetus ja URL, võib olla mitu (välised lingid), vabatahtlik
- [x] lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu, vabatahtlik
- [x] pilt (picture) - vabatahtlik; pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud, max arv 2
- [ ] infograafika - vabatahtlik - kirjeldatud #468  - n arv

**Sisulehe alamosa elemendid:**
Sarnaselt Artikkel tüüpi lehele. Lisamine on vabatahtlik, lehel võib olla mitu alamosa (akordion). Kui lisatakse, siis:
- [x] alamlehe (alamosa) jrk (paragraphSecuenceNo), kohustuslik,
- [x] alampunkti (alamosa) pealkiri (paragraphTitle), kohustuslik, maksimaalne pikkus 50
- [x] alamlehe (alamosa) sisu (paragraphContent), kohustuslik, - WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [x] alamlehe (alamosa) link - webPageLink, nimetus ja URL, võib olla mitu, vabatahtlik
- [ ] alamlehe sees infograafika - vabatahtlik - kirjeldatud #468 
   
**Parema veeru elemendid**
- [x] Sisulehele saab (aga ei pea) lisada parema veeru elemendid, mis vastavad TypeOneArticlePage malli paremale veerule (vt #181 ).
