### ISSUE TITLE
OSKA tulemused lk toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#500]
**Eesmärk, üldkirjeldus:**
Sisuhalduses saab luua ja toimetada OSKA valdkonna „ResultPage“ mallil sisulehte.
Selle lehe keskseks osaks on tabel. Tabeli import #473 

Infoks disain: https://zpl.io/VQEgxzm

**Eeltingimused ja käivitamine:**
- Kasutajal on sisuhalduri õigused.
- Kasutaja on sisuhaldurina sisse loginud.

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- [ ] toimetada lehe sisu 
- [ ] vaadata sisulehe eelvaadet ilma seda lehekülge veebi külastajatele avaldamiseta
- [ ] siduda sisulehte menüüpunktiga
- [ ] avaldada sisulehte

**Sisulehe põhiosa elemendid:**
- [ ] pealkiri (title), kohustuslik, maksimaalne pikkus 50
- [ ] sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- [ ] pilt (picture) - vabatahtlik; pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud, max arv 2
- [ ] sisu (content) - kohustuslik, WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- [ ] video - vabatahtlik (pealkiri ka nagu teistel sisutüüpidel)
- [ ] lingid - webPageLink, nimetus ja URL, võib olla mitu (välised lingid), vabatahtlik
- [ ] lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu, vabatahtlik
- [ ] Peab saama lisada faili (MS Excel), mida portaali külastaja saab tabeli päisest alla laadida (vt disainis - https://zpl.io/VQEgxzm)
- [ ] infograafika - vabatahtlik - kirjeldatud #468 (n arv) - siduda see tüüp ka.
- [ ] tabel - import on kirjeldatud piletis #473 (importimiseks sisutüübil midagi kirjeldada ja sisestada pole vaja, toimib automaatselt importides)

Tabeli struktuur:
- Valdkonna nimi (100 tähemärki)
- Probleemi kirjeldus (500 tähemärki)
- Ettepanek (500 tähemärki)
- Peavastutaja (100 tähemärki)
- Ettepaneku staatus (50 tähemärki)
- Eksperdikogu kommentaar (500 tähemärki)
Muudatus: #553 
   
**Parema veeru elemendid**
- [ ] Sisulehele saab (aga ei pea) lisada parema veeru elemendid, mis vastavad TypeOneArticlePage malli paremale veerule (vt #181 ).

**Viited:**
tabeli import #473 
kuvamine: #501  ja filter #510

**Comment by lsoonvald** [comment]
Tabeli importimiseks pole vajalik sisutüübil midagi lisada, toimib automaatselt.

**Comment by lsoonvald** [comment]
Sisuhaldur saab ainult muuta olemasolevat lehte, lisada ega kustutada ei saa. 
http://test-htm.wiseman.ee:30000/et/node/48979

**Comment by TanelTromp** [comment]
Viga 1: "Pealkiri" väljal puudub maksimaalse pikkuse 50 ühikut nõue

Viga 2: (ilmselt üldine ja võiks teised OSKA sisud ka üle vaadata): "Sisu" element peab olema peale "Sissejuhatus" elementi. Hetkel vastupidi.

**Comment by lsoonvald** [comment]
Viga 1: Lisatud limiit.

Viga 2: Parandatud järjekord.

**Comment by TanelTromp** [comment]
TEST

testlugu: http://htm.twn.ee/et/oska-tulemused/oska-sisuleht-pilet-500be-ja-501fe
