### ISSUE TITLE
Disain leitud vead/parandused vol4

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#503]
- [x] Akordioni värvid on muutunud (ühtlustada üle terve lehe)
- [x] Uudise detailvaates peaks uudise pealkirja kohal olema ka sõna "UUDISED" (vt nt artikli vaates pealkirja kohal olemas see tükk) (Birgit: Värvitoon peaks olema #757575, sama toon ka uudiste listvaates)
- [x] Töölaual akordioni juures imelik valge joon (vt kommentaarides pilt), äkki reso teema?
- [x] Kõikide vaadetes, kus menüü avaneb burgeri alt, peaks burgeri avamisel burgeri ikoon muutuma ristiks, millest saab menüüd sulgeda
- [x] Mobiilis ei ole filtrid ühtlased (vahed erinevad, hint teksti suurused erinevad). Vt pilt kommentaarides (Birgit: 2 viga leidsin, vaata kommentaarides pilte. 1. Dropdown elemendi placeholder teksti ülemine-alumine padding ei ole võrdne. 2. **Toetusprojektide filtri paddingud ei ole võrdsed teiste vaadetega**)

- [x] Avalehel otsingukastis peaks olema placeholder tekst Rubik 14px
- [x] Avaleht > Helesinisel superuudise alal peaks olema UUDISED ja uudise autori nimi ärvitooniga #333333
- [x] Avaleht > Superuudise ja 3-se uudiste bloki vahe peaks väiksem olema
- [x] Avaleht > 3-se uudiste bloki kohal olev UUDISED peaks olema värvitooniga #333333 (palun muuda avalehel uudise 3-se bloki autori nimed ka #333333 tooni)
- [x] Uus tekkinud viga : UUDISED pealkiri peaks joonduma vasakpoolse uudise fotoga vasakult küljelt

- [x] Kõik listvaated, kus on filtreerimine, kontrollida üle, et filtrite placeholder tekstid oleksid 14px Rubik Regular ning et vormiväljade vahed (ülemiste ja alumiste) oleks alati 16px. Hetkel vaated pilla-palla.
- [x] Uus tekkinud viga: Vaadetes, kus on nt Sildid või Liigid vms valikud ja millele vajutades avaneb dropdown, peaks olema viide, et tegu on dropdowniga (allapoole suunatud nool)

_Ei ole uus viga, see kogu aeg olemas olnud. Selectide avamised korras. Uudiste ja sündmuste all pole tegu selectiga vaid hoopis inputiga millel autocomplete küljes. Annab sulle autocomplete soovitusi. Vaata Zeplini_ 

_NB! Näitasin, rääkisn seda ka Andrusega, kuidas Autocorrectiga toime tulla. Leidis, et tuleb see jätta nii nagu on_

- [x] Uus tekkinud viga: Ühtlustada dropdown elemendid (kõik filtri dropdownid peaksid avanema välja alla mitte välja peale)
- [x] Uus viga: Dropdown nool peaks muutuma vastupidiseks dropdowni avanemisel
- [x] Uudise listvaade > Uudise ala peale minnes võiks pealkirjale joon alla tekkida (hetkel on ala küll klikitav, aga pealkirjale ei teki joont alla) (Birgit: Taneliga läbi räägitud, et muudame selle tagasi. Klikitavad on ainult pealkiri ja foto. Sama ka sündmuse vaates, et klikitavaks jääb ainult pealkiri)
- [x] Uudise detailvaade > jaga nupp võiks olla autori ja sissejuhatuse vahel (ainult uudise detailvaates niimoodi!) @madispold 
- [x] Uus viga: Ikooni ja sissejuhatava teksti vahe võiks olla väiksem
- [x] Detailvaadetes Jaga nupp ei tööta ja Jaga nupp peaks olema joondatud pealkirjaga vasakult @madispold 
- [x] Sündmuse listvaade > Valitud sakk ei peaks olema klikitav enam (hetkel muutub nool käeks, kui Nimekiri saki peale minna). Sama viga ka mujal kus sakid kasutusel

_Otsustasime, et jääb nii nagu on_

- [x] Sündmuse listvaade mobiil > nii sündmuse pealkiri kui ka kuupäev peaksid olema fondi suurusega 14px
- [x] Kõikides detailvaadetes, kus on kaardi komponenti kasutatud lehekülje paremas sidebaris, kasutada sama kaarti, mis toetusprojektide vaates (snazzymapsi hall kaart) @skeefee 
- [x] Detailvaadetes, kus on sildid (nt uudised, sündmused), kontrollida üle, et need sildid ei oleks klikitavad (hetkel mõnes kohas on)
- [x] Sündmused > Kalender > Tänase päeva hallil kastil peaks olema ümber joon 1px värvitooniga #9b9b9b
- [x] Sündmused > Kalender > Tänase päeva kuupäeva ümber olev oranž mumm peaks olema ümmargune, mitte ovaal
- [x] Sündmuse detailvaade > Toimumisaeg- ja koht kast > koha ja aja vahel peaks olema terve tühi rida, mitte ebamäärane pisikene tühi ruum
_Keegi oli selle ära parandnaud_
- [x] Kõik detailvaated > Parem pool > 16px-se suurusega sisutekstiga tekstikastide reavahe peaks olema 22px, hetkel väiksem ja tekst liiga koos
- [x] Õppeasutused > Asukohad > Listvaade: Pealkirja all olevate tekstide vaheliste joonte värvitoon peaks olema 2px ja #c7c7c9 (Birgit: mõtlesin vertikaalseid jooni, horisontaalsed jäävad ikka 1px) (Birgit: ei ole ju 2px, palju paksem on?)
- [x] Õppeasutused > Asukohad > Kaart: pinile vajutades avaevas modaalis peaks olema font Rubik (hetkel kuvab mingit muud fonti?) Sama teema ka toetusprojektide kaardi infoaknas.
- [x] Õppeasutused > Toetusprojektid > Haldusüksused: Kaart ei ole klikitav, aga nool muutub käeks, ei peaks nii olema.  @skeefee 

_See peab jääma klikatavaks, rääkisin kokaga. Antud vaate kaart saab sisu juurde modalid/tooltipid w/e._

- [x] Õppeasutused > Toetusprojektid > Haldusüksused > Maakonnad või Vallad/Linnad valik: Valik, mis ei ole valitud, selle tekst võiks olla #2e3374 ja hoveriga joon alla tekkima
- [x] Erialad listvaade: Pealkirja all olevate tekstide vaheliste joonte värvitoon peaks olema 2px ja #c7c7c9 (Birgit: mõtlesin vertikaalseid jooni, horisontaalsed jäävad ikka 1px)
- [x] Erialade listvaade: erialade lisamisel võrdlusesse ja siis Cmd + "Vaata võrdlust" vajutades võiks võrdlus avaneda uues Tabis (Birgit: ei tööta, brauseri ribale tekib tekst "Pop-up blocked")

_Seda pole muutnud, räägiks selle asja läbi Analüütikute kokaga._

- [x] Eriala detailvaade > Sarnased erialad: otsingukasti placeholder tekst peaks olema Rubik 14px 
- [x] Eriala detailvaade > Sarnased erialad: Pealkirja all olevate tekstide vaheliste joonte värvitoon peaks olema 2px ja #c7c7c9 (Birgit: mõtlesin vertikaalseid jooni, horisontaalsed jäävad ikka 1px) (Birgit: ei ole ju 2px, palju paksem on? Sama teema ka erialade listvaates)
- [x]  Eriala detailvaade > Sarnased erialad: tahvli vaates otsingukast ja nupp katki (vt pilti kommentaarides)

_NB! Tegu on Tekstiga, mitte borderiga, Fondi paksust saab reguleerida font-weightiga_
Birgit: Ei saa sellest kommentaarist eelmise punkti kontekstis aru?

- [x] Artikli detailvaade: parempoolses sektsioonis lingile hiirega peale minnes peaks talle joon alla tekkima (Birgit: kõikides artikli vaadetes ei ole korras. Kontrollida üle ka teistes vaadetes, eriti Kontakt blokis e-mail)
- [x] Artikli detailvaade mobiil: video peaks olema full laiuses (hetkel ruumi paremal ja vasakul)

- [x] Uus leitud viga: Video pealkiri läks liiga serva, see peab olema ikka üldise tekstiga sama kaugel vasakust servast

Sanderi leitud vead:
- [x] Toetusprojektide vasak ja parem margin oli desktopis 1rem väiksem võrreldes teiste sarnaste vaadete omadega. 
<img width="1329" alt="screen shot 2018-10-16 at 16 37 58" src="https://user-images.githubusercontent.com/42176503/47026260-b732cb80-d16d-11e8-9568-6a90c3d71cfa.png">

- [x] Toetusprojektide mobla vaates vasakul tabil vasak-border, Paremal tabil border puuudub. Eemaldasin vasakul stepil vasaku borderi.  
<img width="592" alt="screen shot 2018-10-16 at 16 38 53" src="https://user-images.githubusercontent.com/42176503/47026234-a84c1900-d16d-11e8-9612-796e928b0715.png">

- [x] Avaleht 3 Artikli list läheb katki kui ekraani suurus on väiksem kui u. 1024px- 1200px
<img width="1171" alt="screen shot 2018-10-16 at 17 33 13" src="https://user-images.githubusercontent.com/42176503/47026286-c74aab00-d16d-11e8-9094-cc744fdc4bd2.png">

_Mis võib veel juhtuda: Kui pildi alune link on endiselt Kilomeetri pikkune üks sõna, siis hakkab 1 või 2 pilti pisemaks suruma. Reaalses elus seda ei juhtuks. Sõnad ei ole nii pikad. Arvamusi ?_ 

- [x] Tabelide paddingud korda kõikjal. ülemise alumiste paddingud olid tabelites vahemikus 8px-16px edaspidi ainult 8px(0.5rem).
<img width="593" alt="screen shot 2018-10-17 at 13 06 16" src="https://user-images.githubusercontent.com/42176503/47206801-3acd0200-d392-11e8-80e1-efccc50ebdf2.png">

- [x] Lehelingid paremas menüüs sõidavad siust välja.
<img width="421" alt="screen shot 2018-10-17 at 11 00 51" src="https://user-images.githubusercontent.com/42176503/47206894-77006280-d392-11e8-9470-c1aed91c4789.png">

- [x] Sakkidega lehtedel sakkidega anomaalia, kus oranž joon läheb allapoole kui nt sündmuse detailvaatest tagasi sündmuste listvaatesse tulla (vt kommentaarides pilt)

**Comment by birgitpulk** [comment]
![tunnistused___haridusportaal_dev_2](https://user-images.githubusercontent.com/24669779/46395539-5c24c180-c6f5-11e8-91a1-af57fbf46166.png)

**Comment by birgitpulk** [comment]
<img width="801" alt="screen shot 2018-10-07 at 12 08 39" src="https://user-images.githubusercontent.com/24669779/46580249-dd4bc380-ca29-11e8-924c-22e067ba35d2.png">

**Comment by birgitpulk** [comment]
<img width="808" alt="screen shot 2018-10-15 at 13 55 07" src="https://user-images.githubusercontent.com/24669779/46946956-07ccfa80-d082-11e8-8e83-6754970374a1.png">

**Comment by birgitpulk** [comment]
![screen shot 2018-10-23 at 13 36 29](https://user-images.githubusercontent.com/24669779/47354993-e5159400-d6c8-11e8-9ad0-c714fd86885c.png)
![screen shot 2018-10-23 at 13 36 41](https://user-images.githubusercontent.com/24669779/47354994-e5159400-d6c8-11e8-88f5-305020d17185.png)

**Comment by birgitpulk** [comment]
![screen shot 2018-10-23 at 14 06 11](https://user-images.githubusercontent.com/24669779/47356583-30ca3c80-d6cd-11e8-955c-a3b3a3de2c06.png)

**Comment by birgitpulk** [comment]
- [ ] Toetusprojektide mobiilivaate filtri kastid on kitsamad kui teistes vaadetes filtri kastid
- [ ] Toetusprojektide mobiilivaate filtri kastides (dropdownid) on placeholder tekst Regular fondiga, mujal Light

**Comment by madispold** [comment]
Toetusprojektide mobiilivaate filtri kastides (dropdownid) on placeholder tekst Regular fondiga, mujal Light - Tundub nagu korras või ma ei näe seda lihtsalt/ei saa aru :)

Ülejäänud OK. @birgitpulk

**Comment by birgitpulk** [comment]
Toetusprojektide mobiilivaate filtri kastides (dropdownid) on placeholder tekst Regular fondiga, mujal Light: Mu silm nagu näitab, et dropdownidel oleks paksem font, aga inspect ütleb, et mõlemal 300, seega las jääb nii nagu on :D @madispold 

- [ ] Muudame palun teised sakid ka nii, nagu sündmuse vaates. Ehk siis, et valitud sakk ei oleks enam link.
