### ISSUE TITLE
Avalehe uus kujundus ja toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#635]
Back-End täiendused algsele avalehe toimetamise tööle #328 .
 - Lisada avalehe sisutüübile teine "superuudis" samade tingimustega - Kasutaja saab määrata/ muuta avalehel "Super uudise" ja selle avaldamise algus- ja lõppkuupäeva koos kellaajaga.

Front-end uue kujunduse kuvamine, vt desktop: https://zpl.io/bA4zWvo
Mobiilis: https://zpl.io/29o5L8d ja vahepealne suurus: https://zpl.io/aXwWeoM

Uue kujundusega avalehel saab:
- tellida uudiskirja 
- tellida RSS voogu 
- kuvatakse 3 uudist, saab liikuda uudise detailvaatesse, saab avada uudistega lehekülje
- kuvatakse 3 sündmust, saab liikude sündmuse detailvaatesse, saab avada sündmuste lehekülje
- kui on sisestatud üks "super uudis" siis kuvatakse seda esimese bloki "Mis on haridusprtaal" ja uudiskirja tellimise bloki vahel, kui ühtegi superuudist pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
- kui on sisestatud kaks "super uudist" siis kuvatakse teine uudiste ja sündmuste blokkide vahel, kui teist "superuudist" pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
- esimeses blokis "Mis on haridusportaal.." nelja sisuhalduses sistestatud teema kohta, kui on lisatud link, siis see peab avanema.
*** 
- otsingu testimine #613 piletis

**Comment by lsoonvald** [comment]
Back endi poole pealt tehtud.

**Comment by birgitpulk** [comment]
@madispold 

- [ ] Kaks vasakpoolset ikooni ei ole õiged
- [ ] Kollasel taustal superuudise pealkirja värvitoon peaks olema #333333
- [ ] Kas uudiskirja checkboxid saab kuidagi rohkem keskele? Et nad alati oleksid keskel, ükskõik kui pikad need checkboxid on
- [ ] Uudiskirja nupud võiks desktop vaates panna ka üksteise alla
- [ ] Kolmese uudiste bloki UUDISED pealkiri peaks olema #757575 tooni
- [ ] Kolmese uudiste bloki uudiste autorid peaks olema #757575 tooni
- [ ] Sündmuste bloki SÜNDMUSED pealkiri peaks olema #757575 tooni
- [ ] Esile toodud uudise UUDISED nimetus, uudise pealkirja ja autori vahe võiks olla võrdne
- [ ] Kitsamal ekraanisuurusel tekib mingi anomaalia (vt allpool pilti)
- [ ] Mobiilis võiks teha seda taustal olevat kollast kolmnurka veidi väiksemaks
- [ ] Mobiilis võiks teha seda taustal olevat sinist kolmnurka ka veidi väiksemaks

**Comment by birgitpulk** [comment]
<img width="194" alt="screen shot 2018-12-19 at 09 39 19" src="https://user-images.githubusercontent.com/24669779/50206587-88ef8900-0374-11e9-84b7-afb21a517f21.png">

**Comment by TanelTromp** [comment]
Viga 1: "Telli teemad RSS-ga" link on katki st ei tööta

UX-täiendus 1: "siltide tellimisel e-mailile" õnnestumise kinnitav-ilmuv teavitustekst halvasti märgatav - eriti tablet ja mobiilidel, kus fookus eksleb ringi ja tekkiv teavitus "Tänud...." ei paista ilma skrollimata üldse silma

UX-täpsustus 1: kas "Superuudiste" pilt võiks samuti detailvaatesse viia nagu muu sisu puhul avalehel? @birgitpulk 
https://gyazo.com/443e4ba608eaa9c395df9bbadad60ffb

**Comment by birgitpulk** [comment]
- [ ] Mobiilis võiks superuudise värviline kast olla kandiliste nurkadega
- [ ] Ikoonide kohal oleva pealkirja max laius võiks olla sisuga sama lai, hetkel nagu võimaldaks laiemat sinna panna

**Comment by birgitpulk** [comment]
UX-täpsustus 1: jah, nõus

**Comment by lsoonvald** [comment]
Viga 4: Korras.
UX-täiendus 3: Korras.
Viga 5: Peaks korras olema.

**Comment by TanelTromp** [comment]
UX-täiendus uus IE11: see kolmnurk on sisu peal, Zeplinis sisu all ja teises positsioonis:

![pilt](https://user-images.githubusercontent.com/37407917/50283106-90d72800-045d-11e9-8052-e9e6375ea869.png)

**Comment by madispold** [comment]
UX-täiendus uus IE11: Hetkel läks IE's peitu, kuna pseudoelemendi positsioneeringule kiiret lahendust ei leidnud. Mujal käitub korrektselt.

**Comment by birgitpulk** [comment]
- [ ] Avalehe otsingukasti taga olev helesinine kolmnurk muutus (vt kujundusi)
- [ ] Mobiilis kerima hakates muutub esimene ikoon sama tooni nagu hoverdades ikoonid on. Äkki mobiilsetes seadmetes hover maha võtta?
- [ ] Uudiskirja kinnitamisel "Tänud haridusteemade vastu...." tekst peaks olema ka keskele joondatud

**Comment by TanelTromp** [comment]
UX-täiendus 1: endiselt segaselt käitub selle teavituse kuvamisega: Mozilla ja desktop ei ole fookus õiges kohas. Chromega liiga all. Aga suurim probleem on teloga: kuna ei kuva loaderit ja fookus hüppab uudise peale laadimise ajal, siis tekitab segadust, et kas midagi juthus üldse. Birgit testis ka ja arvas, et ei juhtunudki midagi alguses.

**Comment by madispold** [comment]
@birgitpulk @TanelTromp 
Ux-täiendus 1: OK - Lisatud autoscroll.
Birgiti punktid ka üle käidud ja muudetud.

**Comment by TanelTromp** [comment]
UX-täiendus uus: sisuloomes "avaldamata" märgitud uudist ei tohiks super uudisena avalehel kuvada. Hetkel kuvab ja peale vajutades annab error 404. Pigem varjata ära.

**Comment by madispold** [comment]
UX-täiendus uus: OK.
UX-täiendus uus 2: OK.

**Comment by TanelTromp** [comment]
TEST 

- [ ] Lisada avalehe sisutüübile teine "superuudis" samade tingimustega - Kasutaja saab määrata/ muuta avalehel "Super uudise" ja selle avaldamise algus- ja lõppkuupäeva koos kellaajaga.

- [ ] Front-end uue kujunduse kuvamine, vt desktop: https://zpl.io/bA4zWvo
Mobiilis? @birgitpulk

Uue kujundusega avalehel saab:

- [ ] tellida uudiskirja
- [ ] tellida RSS voogu

- [ ] kuvatakse 3 uudist, saab liikuda uudise detailvaatesse, saab avada uudistega lehekülje

- [ ] kuvatakse 3 sündmust, saab liikude sündmuse detailvaatesse, saab avada sündmuste lehekülje
kui on sisestatud üks "super uudis" siis kuvatakse seda esimese bloki "Mis on haridusprtaal" ja uudiskirja tellimise bloki vahel, kui ühtegi superuudist pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).

- [ ] kui on sisestatud kaks "super uudist" siis kuvatakse teine uudiste ja sündmuste blokkide vahel, kui teist "superuudist" pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
esimeses blokis "Mis on haridusportaal.." nelja sisuhalduses sistestatud teema kohta, kui on lisatud link, siis see peab avanema.

**Comment by TanelTromp** [comment]
l
